//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificateTable
    {
        public int CertificateID { get; set; }
        public int EmployeeID { get; set; }
        public string CertificateName { get; set; }
        public string CertificateAuthority { get; set; }
        public string LevelCertification { get; set; }
        public System.DateTime FromYear { get; set; }
    
        public virtual EmployeeTable EmployeeTable { get; set; }
    }
}
