//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTable
    {
        public int JobID { get; set; }
        public int JobCategotyID { get; set; }
        public string JobTitle { get; set; }
        public string JobRequirments { get; set; }
        public string JobDetails { get; set; }
    
        public virtual JobCategoryTable JobCategoryTable { get; set; }
    }
}
