//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostJobTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PostJobTable()
        {
            this.JobApplyTables = new HashSet<JobApplyTable>();
        }
    
        public int PostJobID { get; set; }
        public int UserID { get; set; }
        public int CompanyID { get; set; }
        public int JobID { get; set; }
        public int RequiredPerson { get; set; }
        public string Qualification { get; set; }
        public string MinimumExperience { get; set; }
        public int AgeLimit { get; set; }
        public string MarriedStatus { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime ShortlistDate { get; set; }
        public System.DateTime InterviewDate { get; set; }
        public int JobStatusID { get; set; }
        public string Description { get; set; }
        public int JobCategoryID { get; set; }
    
        public virtual CompanyTable CompanyTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobApplyTable> JobApplyTables { get; set; }
        public virtual JobCategoryTable JobCategoryTable { get; set; }
        public virtual JobStatusTable JobStatusTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
